name: Cypress Automation

on:
  push:
    branches:
      - main

  pull_request:
    branches:
      - main

jobs:
  cypress-tests:

    runs-on: ubuntu-latest

    steps:

      - name: Checkout do código
        uses: actions/checkout@v4

      - name: Configurar Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: npm

      - name: Instalar dependências
        run: npm ci

      - name: Verificar versão do Cypress
        run: npx cypress version

      - name: Executar testes
        run: npm test
        env:
          CYPRESS_TRELLO_KEY: ${{ secrets.TRELLO_KEY }}
          CYPRESS_TRELLO_TOKEN: ${{ secrets.TRELLO_TOKEN }}
          CYPRESS_TRELLO_ACTION_ID: ${{ secrets.TRELLO_ACTION_ID }}

      - name: Publicar relatório Mochawesome
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: Mochawesome-Report
          path: mochawesome-report/

      - name: Publicar Screenshots
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: Screenshots
          path: cypress/screenshots/

      - name: Publicar Vídeos
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: Videos
          path: cypress/videos/